// Generated by scripts/optimize-photography.py.
import photo0_480 from '@/assets/images/business-case-people-480.webp';
import photo0_800 from '@/assets/images/business-case-people-800.webp';
import photo0_1200 from '@/assets/images/business-case-people-1200.webp';
import photo0_1536 from '@/assets/images/business-case-people-1536.webp';
import photo1_480 from '@/assets/images/executive-travel-portrait-480.webp';
import photo1_800 from '@/assets/images/executive-travel-portrait-800.webp';
import photo1_1200 from '@/assets/images/executive-travel-portrait-1200.webp';
import photo1_1448 from '@/assets/images/executive-travel-portrait-1448.webp';
import photo2_480 from '@/assets/images/platform-duty-of-care-480.webp';
import photo2_800 from '@/assets/images/platform-duty-of-care-800.webp';
import photo2_1200 from '@/assets/images/platform-duty-of-care-1200.webp';
import photo2_1536 from '@/assets/images/platform-duty-of-care-1536.webp';
import photo3_480 from '@/assets/images/platform-hero-traveler-480.webp';
import photo3_800 from '@/assets/images/platform-hero-traveler-800.webp';
import photo3_1200 from '@/assets/images/platform-hero-traveler-1200.webp';
import photo3_1448 from '@/assets/images/platform-hero-traveler-1448.webp';
import photo4_480 from '@/assets/images/platform-human-care-480.webp';
import photo4_800 from '@/assets/images/platform-human-care-800.webp';
import photo4_1200 from '@/assets/images/platform-human-care-1200.webp';
import photo4_1254 from '@/assets/images/platform-human-care-1254.webp';
import photo5_480 from '@/assets/images/platform-local-experiences-480.webp';
import photo5_800 from '@/assets/images/platform-local-experiences-800.webp';
import photo5_1200 from '@/assets/images/platform-local-experiences-1200.webp';
import photo5_1600 from '@/assets/images/platform-local-experiences-1600.webp';

export const photography = {
  'business-case-people': { src: photo0_1200, srcSet: `${photo0_480} 480w, ${photo0_800} 800w, ${photo0_1200} 1200w, ${photo0_1536} 1536w`, width: 1536, height: 1024 },
  'executive-travel-portrait': { src: photo1_1200, srcSet: `${photo1_480} 480w, ${photo1_800} 800w, ${photo1_1200} 1200w, ${photo1_1448} 1448w`, width: 1448, height: 1086 },
  'platform-duty-of-care': { src: photo2_1200, srcSet: `${photo2_480} 480w, ${photo2_800} 800w, ${photo2_1200} 1200w, ${photo2_1536} 1536w`, width: 1536, height: 1024 },
  'platform-hero-traveler': { src: photo3_1200, srcSet: `${photo3_480} 480w, ${photo3_800} 800w, ${photo3_1200} 1200w, ${photo3_1448} 1448w`, width: 1448, height: 1086 },
  'platform-human-care': { src: photo4_1200, srcSet: `${photo4_480} 480w, ${photo4_800} 800w, ${photo4_1200} 1200w, ${photo4_1254} 1254w`, width: 1254, height: 1254 },
  'platform-local-experiences': { src: photo5_1200, srcSet: `${photo5_480} 480w, ${photo5_800} 800w, ${photo5_1200} 1200w, ${photo5_1600} 1600w`, width: 1672, height: 941 },
};
