// Generated by scripts/optimize-photography.py.
import photo0_480 from '@/assets/images/ai-hero-intelligence-trip-480.webp';
import photo0_800 from '@/assets/images/ai-hero-intelligence-trip-800.webp';
import photo0_1200 from '@/assets/images/ai-hero-intelligence-trip-1200.webp';
import photo0_1448 from '@/assets/images/ai-hero-intelligence-trip-1448.webp';
import photo1_480 from '@/assets/images/airport-group-travelers-480.webp';
import photo1_800 from '@/assets/images/airport-group-travelers-800.webp';
import photo1_1200 from '@/assets/images/airport-group-travelers-1200.webp';
import photo1_1600 from '@/assets/images/airport-group-travelers-1600.webp';
import photo2_480 from '@/assets/images/Avatar-480.webp';
import photo2_800 from '@/assets/images/Avatar-800.webp';
import photo2_1200 from '@/assets/images/Avatar-1200.webp';
import photo2_1337 from '@/assets/images/Avatar-1337.webp';
import photo3_480 from '@/assets/images/business-case-people-480.webp';
import photo3_800 from '@/assets/images/business-case-people-800.webp';
import photo3_1200 from '@/assets/images/business-case-people-1200.webp';
import photo3_1536 from '@/assets/images/business-case-people-1536.webp';
import photo4_480 from '@/assets/images/executive-travel-portrait-480.webp';
import photo4_800 from '@/assets/images/executive-travel-portrait-800.webp';
import photo4_1200 from '@/assets/images/executive-travel-portrait-1200.webp';
import photo4_1448 from '@/assets/images/executive-travel-portrait-1448.webp';
import photo5_480 from '@/assets/images/platform-duty-of-care-480.webp';
import photo5_800 from '@/assets/images/platform-duty-of-care-800.webp';
import photo5_1200 from '@/assets/images/platform-duty-of-care-1200.webp';
import photo5_1536 from '@/assets/images/platform-duty-of-care-1536.webp';
import photo6_480 from '@/assets/images/platform-hero-traveler-480.webp';
import photo6_800 from '@/assets/images/platform-hero-traveler-800.webp';
import photo6_1200 from '@/assets/images/platform-hero-traveler-1200.webp';
import photo6_1448 from '@/assets/images/platform-hero-traveler-1448.webp';
import photo7_480 from '@/assets/images/platform-human-care-480.webp';
import photo7_800 from '@/assets/images/platform-human-care-800.webp';
import photo7_1200 from '@/assets/images/platform-human-care-1200.webp';
import photo7_1254 from '@/assets/images/platform-human-care-1254.webp';
import photo8_480 from '@/assets/images/platform-local-experiences-480.webp';
import photo8_800 from '@/assets/images/platform-local-experiences-800.webp';
import photo8_1200 from '@/assets/images/platform-local-experiences-1200.webp';
import photo8_1600 from '@/assets/images/platform-local-experiences-1600.webp';
import photo9_480 from '@/assets/images/solutions-hero-airport-team-480.webp';
import photo9_800 from '@/assets/images/solutions-hero-airport-team-800.webp';
import photo9_1200 from '@/assets/images/solutions-hero-airport-team-1200.webp';
import photo9_1448 from '@/assets/images/solutions-hero-airport-team-1448.webp';
import photo10_480 from '@/assets/images/solutions-hero-departure-team-480.webp';
import photo10_800 from '@/assets/images/solutions-hero-departure-team-800.webp';
import photo10_1200 from '@/assets/images/solutions-hero-departure-team-1200.webp';
import photo10_1448 from '@/assets/images/solutions-hero-departure-team-1448.webp';
import photo11_480 from '@/assets/images/solutions-hero-shared-view-480.webp';
import photo11_800 from '@/assets/images/solutions-hero-shared-view-800.webp';
import photo11_1200 from '@/assets/images/solutions-hero-shared-view-1200.webp';
import photo11_1448 from '@/assets/images/solutions-hero-shared-view-1448.webp';

export const photography = {
  'ai-hero-intelligence-trip': { src: photo0_1200, srcSet: `${photo0_480} 480w, ${photo0_800} 800w, ${photo0_1200} 1200w, ${photo0_1448} 1448w`, width: 1448, height: 1086 },
  'airport-group-travelers': { src: photo1_1200, srcSet: `${photo1_480} 480w, ${photo1_800} 800w, ${photo1_1200} 1200w, ${photo1_1600} 1600w`, width: 1774, height: 887 },
  'Avatar': { src: photo2_1200, srcSet: `${photo2_480} 480w, ${photo2_800} 800w, ${photo2_1200} 1200w, ${photo2_1337} 1337w`, width: 1337, height: 1104 },
  'business-case-people': { src: photo3_1200, srcSet: `${photo3_480} 480w, ${photo3_800} 800w, ${photo3_1200} 1200w, ${photo3_1536} 1536w`, width: 1536, height: 1024 },
  'executive-travel-portrait': { src: photo4_1200, srcSet: `${photo4_480} 480w, ${photo4_800} 800w, ${photo4_1200} 1200w, ${photo4_1448} 1448w`, width: 1448, height: 1086 },
  'platform-duty-of-care': { src: photo5_1200, srcSet: `${photo5_480} 480w, ${photo5_800} 800w, ${photo5_1200} 1200w, ${photo5_1536} 1536w`, width: 1536, height: 1024 },
  'platform-hero-traveler': { src: photo6_1200, srcSet: `${photo6_480} 480w, ${photo6_800} 800w, ${photo6_1200} 1200w, ${photo6_1448} 1448w`, width: 1448, height: 1086 },
  'platform-human-care': { src: photo7_1200, srcSet: `${photo7_480} 480w, ${photo7_800} 800w, ${photo7_1200} 1200w, ${photo7_1254} 1254w`, width: 1254, height: 1254 },
  'platform-local-experiences': { src: photo8_1200, srcSet: `${photo8_480} 480w, ${photo8_800} 800w, ${photo8_1200} 1200w, ${photo8_1600} 1600w`, width: 1672, height: 941 },
  'solutions-hero-airport-team': { src: photo9_1200, srcSet: `${photo9_480} 480w, ${photo9_800} 800w, ${photo9_1200} 1200w, ${photo9_1448} 1448w`, width: 1448, height: 1086 },
  'solutions-hero-departure-team': { src: photo10_1200, srcSet: `${photo10_480} 480w, ${photo10_800} 800w, ${photo10_1200} 1200w, ${photo10_1448} 1448w`, width: 1448, height: 1086 },
  'solutions-hero-shared-view': { src: photo11_1200, srcSet: `${photo11_480} 480w, ${photo11_800} 800w, ${photo11_1200} 1200w, ${photo11_1448} 1448w`, width: 1448, height: 1086 },
};
