from pathlib import Path
from PIL import Image
import json

root = Path(__file__).resolve().parents[1]
assets = root / 'src/assets/images'
imports = []
entries = []
original_total = 0
largest_total = 0
for index, source in enumerate(sorted(assets.glob('*.png'))):
    original_total += source.stat().st_size
    with Image.open(source) as image:
        image = image.convert('RGB')
        widths = sorted(set(min(w, image.width) for w in (480, 800, 1200, 1600)))
        variants = []
        for width in widths:
            height = round(image.height * width / image.width)
            output = assets / f'{source.stem}-{width}.webp'
            image.resize((width, height), Image.Resampling.LANCZOS).save(output, 'WEBP', quality=80, method=6)
            name = f'photo{index}_{width}'
            imports.append(f"import {name} from '@/assets/images/{output.name}';")
            variants.append((name, width))
        largest_total += output.stat().st_size
        srcset = ', '.join('${' + name + '} ' + str(width) + 'w' for name, width in variants)
        entries.append(f"  '{source.stem}': {{ src: {variants[-2][0]}, srcSet: `{srcset}`, width: {image.width}, height: {image.height} }},")
        print(f'{source.name}: {source.stat().st_size:,} -> {output.stat().st_size:,} bytes (largest variant)')
(root / 'src/content/photography.ts').write_text('// Generated by scripts/optimize-photography.py.\n' + '\n'.join(imports) + '\n\nexport const photography = {\n' + '\n'.join(entries) + '\n};\n', encoding='utf-8')
print(f'Total: {original_total:,} -> {largest_total:,} bytes; {100*(1-largest_total/original_total):.1f}% smaller')
